// flow-typed signature: 98dcd9a715fa5ebd830548d9746cd7d3
// flow-typed version: <<STUB>>/flag-icon-css_v^2.8.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flag-icon-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flag-icon-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flag-icon-css/assets/docs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flag-icon-css/assets/docs.js' {
  declare module.exports: $Exports<'flag-icon-css/assets/docs'>;
}
