// flow-typed signature: 38ce41a0a29530cf50c0796e69c74d80
// flow-typed version: <<STUB>>/nsp_v^2.7.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nsp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nsp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nsp/lib/check' {
  declare module.exports: any;
}

declare module 'nsp/lib/commands/check' {
  declare module.exports: any;
}

declare module 'nsp/lib/commands/defaults' {
  declare module.exports: any;
}

declare module 'nsp/lib/commands/root' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/codeclimate' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/default' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/index' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/json' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/none' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/quiet' {
  declare module.exports: any;
}

declare module 'nsp/lib/formatters/summary' {
  declare module.exports: any;
}

declare module 'nsp/lib/index' {
  declare module.exports: any;
}

declare module 'nsp/lib/utils/config' {
  declare module.exports: any;
}

declare module 'nsp/lib/utils/sanitizePackage' {
  declare module.exports: any;
}

declare module 'nsp/lib/utils/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nsp/lib/check.js' {
  declare module.exports: $Exports<'nsp/lib/check'>;
}
declare module 'nsp/lib/commands/check.js' {
  declare module.exports: $Exports<'nsp/lib/commands/check'>;
}
declare module 'nsp/lib/commands/defaults.js' {
  declare module.exports: $Exports<'nsp/lib/commands/defaults'>;
}
declare module 'nsp/lib/commands/root.js' {
  declare module.exports: $Exports<'nsp/lib/commands/root'>;
}
declare module 'nsp/lib/formatters/codeclimate.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/codeclimate'>;
}
declare module 'nsp/lib/formatters/default.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/default'>;
}
declare module 'nsp/lib/formatters/index.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/index'>;
}
declare module 'nsp/lib/formatters/json.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/json'>;
}
declare module 'nsp/lib/formatters/none.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/none'>;
}
declare module 'nsp/lib/formatters/quiet.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/quiet'>;
}
declare module 'nsp/lib/formatters/summary.js' {
  declare module.exports: $Exports<'nsp/lib/formatters/summary'>;
}
declare module 'nsp/lib/index.js' {
  declare module.exports: $Exports<'nsp/lib/index'>;
}
declare module 'nsp/lib/utils/config.js' {
  declare module.exports: $Exports<'nsp/lib/utils/config'>;
}
declare module 'nsp/lib/utils/sanitizePackage.js' {
  declare module.exports: $Exports<'nsp/lib/utils/sanitizePackage'>;
}
declare module 'nsp/lib/utils/usage.js' {
  declare module.exports: $Exports<'nsp/lib/utils/usage'>;
}
