// flow-typed signature: 9669a8ccd6e71a0a0a18f234687c620b
// flow-typed version: <<STUB>>/postcss-discard-comments_v^2.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-discard-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-discard-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-discard-comments/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-discard-comments/dist/lib/commentParser' {
  declare module.exports: any;
}

declare module 'postcss-discard-comments/dist/lib/commentRemover' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-discard-comments/dist/index.js' {
  declare module.exports: $Exports<'postcss-discard-comments/dist/index'>;
}
declare module 'postcss-discard-comments/dist/lib/commentParser.js' {
  declare module.exports: $Exports<'postcss-discard-comments/dist/lib/commentParser'>;
}
declare module 'postcss-discard-comments/dist/lib/commentRemover.js' {
  declare module.exports: $Exports<'postcss-discard-comments/dist/lib/commentRemover'>;
}
