// flow-typed signature: 5c1e2fa84928b058051bc60bed46ef1b
// flow-typed version: <<STUB>>/postcss-each_v^0.10.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-each'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-each' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-each/index.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-each/index.es5.js' {
  declare module.exports: $Exports<'postcss-each/index.es5'>;
}
declare module 'postcss-each/index' {
  declare module.exports: $Exports<'postcss-each'>;
}
declare module 'postcss-each/index.js' {
  declare module.exports: $Exports<'postcss-each'>;
}
